source "https://rubygems.org"
# comment "c_lexer" if generating arm version of atome
gem "rubocop"
#gem "c_lexer"
gem "filewatcher"
gem "image_size"
# gem "opal", "1.0.5"
gem "opal"
gem "opal-jquery"
gem "rake"
gem "uglifier"
gem "parser"
gem "faye-websocket", "0.11.0"
# if fays websocket fail to install event machine use : gem install eventmachine -- --with-openssl-dir=/usr/local/opt/openssl@1.1
gem "puma", "5.0.2"
gem "rack"
gem "rack-unreloader"
gem "roda", "2.26.0"
gem "sequel"
gem "rufus-scheduler"
gem "sqlite3"
gem "mail"
