Opal.queue(function(Opal) {/* Generated by Opal 1.7.3 */
  var $gvars = Opal.gvars, nil = Opal.nil;

  return ($gvars.host = "browser")
});

Opal.queue(function(Opal) {/* Generated by Opal 1.7.3 */
  var $hash2 = Opal.hash2, $send = Opal.send, self = Opal.top, nil = Opal.nil, g = nil;

  Opal.add_stubs('new,group');
  
  window.addEventListener('error', function(e) {
  console.log("---> Now we can log error in a file if needed : " + e.message);
});;
  self.$new($hash2(["atome"], {"atome": "group"}));
  $send(self, 'new', [$hash2(["sanitizer"], {"sanitizer": "group"})], function $$1(params){
    
    if (params == null) params = nil;
    return $hash2([], {});});
  return (g = self.$group(["b1", "b2"]));
});
