# frozen_string_literal: true

# require without relative is needed when using Opal
require 'fileutils'
require 'securerandom'
require 'atome/version'
require 'atome/genesis/genesis'
require 'atome/kernel/black_matter'
require 'atome/kernel/universe'
require 'atome/helpers/essentials'
require 'renderers/renderer'
require 'atome/helpers/color_helper/color'
require 'atome/extensions/atome'
require 'atome/extensions/mathematics'
require 'atome/atome'
require 'atome/genesis/atome'
require 'atome/presets/atome'
require 'atome/genesis/particles/atome'
require 'atome/genesis/particles/communication'
require 'atome/genesis/particles/effect'
require 'atome/genesis/particles/event'
require 'atome/genesis/particles/geometry'
require 'atome/genesis/particles/hierarchy'
require 'atome/genesis/particles/identity'
require 'atome/genesis/particles/material'
require 'atome/genesis/particles/property'
require 'atome/genesis/particles/security'
require 'atome/genesis/particles/spatial'
require 'atome/genesis/particles/time'
require 'atome/genesis/particles/utility'
require 'atome/helpers/utilities'
require 'atome/helpers/security'
require 'renderers/html/index'
require 'renderers/headless/index'
require 'renderers/server/index'
require 'atome/helpers/sanitizer'
require 'atome/genesis/sparkle'
require 'eVe/lib/eVe'
# require 'eVe'
# gem_spec = Gem::Specification.find_by_name(gem_name)
# gem_path = gem_spec.gem_dir
# puts "Le chemin vers la gemme '#{gem_name}' est '#{gem_path}'"
