# frozen_string_literal: true
# relative is needed when using ruby wasm
require 'fileutils'
require 'securerandom'
require_relative './atome/version'
require_relative './atome/genesis/genesis'
require_relative 'atome/kernel/black_matter'
require_relative './atome/kernel/universe'
require_relative './atome/helpers/essentials'
require_relative './renderers/renderer'
require_relative './atome/helpers/color_helper/color'
require_relative './atome/extensions/atome'
require_relative './atome/extensions/mathematics'
require_relative './atome/atome'
require_relative './atome/genesis/atome'
require_relative './atome/presets/atome'
require_relative './atome/genesis/particles/atome'
require_relative './atome/genesis/particles/communication'
require_relative './atome/genesis/particles/effect'
require_relative './atome/genesis/particles/event'
require_relative './atome/genesis/particles/geometry'
require_relative './atome/genesis/particles/hierarchy'
require_relative './atome/genesis/particles/identity'
require_relative './atome/genesis/particles/material'
require_relative './atome/genesis/particles/property'
require_relative './atome/genesis/particles/security'
require_relative './atome/genesis/particles/spatial'
require_relative './atome/genesis/particles/time'
require_relative './atome/genesis/particles/utility'
require_relative './atome/helpers/utilities'
require_relative './atome/helpers/security'
require_relative './renderers/html/index_relative'
require_relative './renderers/headless/index_relative'
require_relative './renderers/server/index_relative'
require_relative './atome/helpers/sanitizer'
require_relative './atome/genesis/sparkle'
require_relative './eVe/lib/eVe_relative'

# require 'eVe'
# gem_spec = Gem::Specification.find_by_name(gem_name)
# gem_path = gem_spec.gem_dir
# puts "Le chemin vers la gemme '#{gem_name}' est '#{gem_path}'"