# frozen_string_literal: true

# require without relative is needed when using Opal
require 'fileutils'
require 'securerandom'
require 'atome/version'
require 'atome/genesis/genesis'
require 'atome/kernel/black_matter'
require 'atome/kernel/universe'
require 'atome/utilities/essentials'
require 'renderers/renderer'
require 'atome/utilities/color_helper/color'
require 'atome/extensions/atome'
require 'atome/extensions/mathematics'
require 'atome/atome'
require 'atome/genesis/atomes'
require 'atome/presets/atome'
require 'atome/genesis/particles/atome'
require 'atome/genesis/particles/communication'
require 'atome/genesis/particles/effect'
require 'atome/genesis/particles/event'
require 'atome/genesis/particles/geometry'
require 'atome/genesis/particles/hierarchy'
require 'atome/genesis/particles/identity'
require 'atome/genesis/particles/material'
require 'atome/genesis/particles/property'
require 'atome/genesis/particles/security'
require 'atome/genesis/particles/spatial'
require 'atome/genesis/particles/time'
require 'atome/genesis/particles/utility'
require 'atome/utilities/utilities'
require 'atome/utilities/security'
require 'renderers/html/index'
require 'renderers/headless/index'
require 'renderers/server/index'
require 'atome/utilities/sanitizer'
require 'atome/genesis/sparkle'
require 'molecules/init'
# require 'eVe/lib/eVe'
