# frozen_string_literal: true

require 'fileutils'
require 'securerandom'
require 'atome/version'
require 'atome/genesis/genesis'
require 'atome/kernel/essentials'
require 'atome/kernel/universe'
# require 'atome/kernel/batch'
require 'atome/helpers/essentials'
require 'renderers/renderer'
require 'atome/helpers/color_helper/color'
require 'atome/extensions/atome'
require 'atome/extensions/mathematics'
require 'atome/atome'
require 'atome/helpers/callbacks'
require 'atome/genesis/generators/atome'
require 'atome/presets/atome'

require 'atome/genesis/generators/communication'
require 'atome/genesis/generators/effect'
require 'atome/genesis/generators/event'
require 'atome/genesis/generators/geometry'
require 'atome/genesis/generators/identity'
require 'atome/genesis/generators/material'
require 'atome/genesis/generators/spatial'
require 'atome/genesis/generators/time'
require 'atome/genesis/generators/utility'
require 'atome/helpers/utilities'
if RUBY_ENGINE.downcase == 'opal'
  require 'renderers/browser/browser'
  require 'renderers/html/html'
end
require 'renderers/headless/headless'
require 'renderers/server/server'
require 'atome/extensions/matrix'
require 'atome/helpers/sanitizer'
require 'atome/genesis/group/group'
require 'atome/genesis/sparkle'
