module Atome
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  def *: -> untyped

  def +: -> untyped

  def -: -> untyped

  def /: -> untyped

  def add: -> untyped

  def add_to_array: -> untyped

  def add_to_hash: -> untyped

  def apply_style: -> untyped

  def atome_common: -> untyped

  def auto_render_generator: -> untyped

  def box: -> untyped

  def build_atome: -> Atome

  def build_option: -> untyped

  def build_particle: -> untyped

  def build_render: -> untyped

  def build_sanitizer: -> untyped

  def calculate_sha: -> untyped

  def circle: -> untyped

  def detach_atome: -> untyped

  def each_with_index: -> untyped

  def format_matrix: -> untyped

  def geolocation: -> untyped

  def get_column: -> untyped

  def get_column_or_row: -> untyped

  def get_row: -> untyped

  def matrix: -> untyped

  def ping: -> untyped

  def set: -> untyped

  def sort_callback: -> untyped

  def up?: -> untyped

  def visuals: -> untyped

  private

  def atome_parsing: -> untyped

  def found_parents_and_renderers: -> untyped

  def new_render_engine: -> untyped
end
