module Atome
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  def add: -> untyped

  def add_to_array: -> untyped

  def add_to_hash: -> untyped

  def apply_style: -> untyped

  def auto_render_generator: -> untyped

  def build_atome: -> Atome

  def build_option: -> untyped

  def build_particle: -> untyped

  def build_render: -> untyped

  def build_sanitizer: -> untyped

  def format_matrix: -> untyped

  def get_column: -> untyped

  def get_column_or_row: -> untyped

  def get_row: -> untyped

  def matrix: -> untyped

  def set: -> untyped

  def sort_callback: -> untyped
end
