module BrowserHelper
  @enter_action_proc: untyped
  @leave_action_proc: untyped

  def self.anim_convertor: -> untyped

  def self.anim_value_analysis: -> untyped

  def self.browser_over_enter: -> untyped

  def self.browser_over_leave: -> untyped

  def self.send_anim_to_js: -> untyped
end
