#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

def delete_all(dir)
  Dir.foreach(dir) do |e|
    # Don't bother with . and ..
    next if %w[. ..].include? e
    fullname = dir + File::Separator + e
    if FileTest.directory?(fullname)
      delete_all(fullname)
    else
      File.delete(fullname)
    end
  end
  Dir.delete(dir)
end

def run(option = :browser, location = nil)
  case option
  when :server
    require 'atome'
    if location
      `cd ./#{location}/server;rackup --server puma --port 9292  --env production`
    else
      `cd ./server;rackup --server puma --port 9292  --env production`
    end
  when :browser
    if location
      `cd ./#{location}/build;open index.html`
    else
      `cd ./build;open index.html`
    end
  when :osx
    require 'webview_ruby'
    webview = WebviewRuby::Webview.new
    webview.set_title('atome')
    webview.set_size(480, 360)
    if location
      webview.navigate("file:/#{`pwd`}/#{location}/build/index.html")
    else
      webview.navigate("file:#{`pwd`.chomp}/build/index.html")
    end
    webview.run
  else
    # nothing for now
  end

end

case ARGV[0]
when 'create'
  project_name = ARGV[1]
  force = ARGV[2]
  delete_all(project_name) if force == 'force'
  Dir.mkdir project_name.to_s
  current_path = `pwd`.chomp
  gem_assets_location = File.join(File.dirname(__FILE__), '../vendor/assets/')
  app_builder_helpers = File.join(File.dirname(__FILE__), '../app_builder_helpers')
  target_template_location = "#{current_path}/#{project_name}"
  Dir.entries(gem_assets_location).select do |entry|
    if File.join(entry) && !%w[. ..].include?(entry)
      entry = "#{File.dirname(__FILE__)}/../vendor/assets/#{entry}"
      FileUtils.cp_r entry, target_template_location
    end
  end
  # now run the rake task to build the needed libraries (atome, renderers, etc...)
  `cd #{app_builder_helpers};rake system_builder #{current_path}/#{project_name}`
  run(:server, project_name)
when 'run'
  case ARGV[1]
  when 'android'
  when 'browser'
    run(:browser)
  when 'freebsd'
  when 'ios'
  when 'linux'
  when 'osx'
    run(:osx)
  when 'server'
    run(:server)
  when 'windows'
  else
    # type code here
  end
else
  # type code here
end
