# render methods
module RenderHtml
  include HtmlHelpers
  include AudioProcessorHtml
  include CommunicationProcessorHtml
  include EffectProcessorHtml
  include EventProcessorHtml
  include GeometryProcessorHtml
  include HelperProcessorHtml
  include HierarchyProcessorHtml
  include IdentityProcessorHtml
  include MediaProcessorHtml
  include SpatialProcessorHtml
  include UtilityProcessorHtml
  include MaterialProcessorHtml
  include AudioHtml
  include CommunicationHtml
  include EffectHtml
  include EventHtml
  include GeometryHtml
  include HelperHtml
  include HierarchyHtml
  include IdentityHtml
  include MediaHtml
  include SpatialHtml
  include UtilityHtml
  include MaterialHtml
  include JSUtils
end