# ruby main Object extensions
require "atome/extensions/ruby/object"
# default_value
require "atome/environment/default_values"
# opal specific
require "atome/extensions/opal/opal_audio"
require "atome/extensions/opal/opal_code_editor"
require "atome/extensions/opal/opal_database"
require "atome/extensions/opal/opal_generator.rb"
require "atome/extensions/opal/opal_helpers"
require "atome/extensions/opal/opal_io"
require "atome/extensions/opal/opal_timer"
require "atome/extensions/opal/opal_video"
require "atome/extensions/opal/opal_jquery"
# render helper
require "atome/renderers/html/processors/communication"
require "atome/renderers/html/processors/effect"
require "atome/renderers/html/processors/event"
require "atome/renderers/html/processors/geometry"
require "atome/renderers/html/processors/helper"
require "atome/renderers/html/processors/hierarchy"
require "atome/renderers/html/processors/identity"
require "atome/renderers/html/processors/media"
require "atome/renderers/html/processors/spatial"
require "atome/renderers/html/processors/utility"
require "atome/renderers/html/processors/material"
# html renderer
require "atome/renderers/html/properties/communication"
require "atome/renderers/html/properties/effect"
require "atome/renderers/html/properties/event"
require "atome/renderers/html/properties/geometry"
require "atome/renderers/html/properties//generator"
require "atome/renderers/html/properties/helper"
require "atome/renderers/html/properties/hierarchy"
require "atome/renderers/html/properties/identity"
require "atome/renderers/html/properties/media"
require "atome/renderers/html/properties/inputs"
require "atome/renderers/html/properties/spatial"
require "atome/renderers/html/properties/utility"
require "atome/renderers/html/properties/material"
require "atome/renderers/html/helpers/helpers"
require "atome/renderers/html"
# generated property
require "atome/generated_methods/communications"
require "atome/generated_methods/effects"
require "atome/generated_methods/events"
require "atome/generated_methods/geometries"
require "atome/generated_methods/generator"
require "atome/generated_methods/helpers"
require "atome/generated_methods/hierarchies"
require "atome/generated_methods/identities"
require "atome/generated_methods/medias"
require "atome/generated_methods/inputs"
require "atome/generated_methods/spatials"
require "atome/generated_methods/utilities"
require "atome/generated_methods/materials"
# property processors
require "atome/processors/communication"
require "atome/processors/effect"
require "atome/processors/event"
require "atome/processors/geometry"
require "atome/processors/helper"
require "atome/processors/hierarchy"
require "atome/processors/identity"
require "atome/processors/media"
require "atome/processors/input"
require "atome/processors/spatial"
require "atome/processors/utility"
require "atome/processors/material"
# helpers
require "atome/helpers/atome_helpers"
require "atome/helpers/internal_helpers"
require "atome/generated_methods/atome_methods"
# main atome builder
require "atome/generated_methods/batch"
require "atome/builder/properties"
#Quark.genesis
require "atome/builder/atome_generator"
# Atome helper (methods available at main Object level)
require "atome/extensions/atome_extensions"
require "atome/extensions/atome_utilities"
# class to create a new device
require "atome/environment/device"
# elementary atomes for basic environment
require "atome/environment/initialize"
# methods to simplify object creation
require "atome/generated_methods/atome_object_creator"
require "atome/extensions/atome_code_creator"