# ruby main Object extensions
require "atome/extensions/object/hash"
# default_value
require "atome/environment/default_values"
# opal specific
require "atome/extensions/opal/opal_helpers"
require "atome/extensions/opal/opal_jquery"
# render helper
require "atome/renderers/html/processors/audio"
require "atome/renderers/html/processors/communication"
require "atome/renderers/html/processors/effect"
require "atome/renderers/html/processors/event"
require "atome/renderers/html/processors/geometry"
require "atome/renderers/html/processors/helper"
require "atome/renderers/html/processors/hierarchy"
require "atome/renderers/html/processors/identity"
require "atome/renderers/html/processors/media"
require "atome/renderers/html/processors/spatial"
require "atome/renderers/html/processors/utility"
require "atome/renderers/html/processors/visual"
# html renderer
require "atome/renderers/html//properties/audio"
require "atome/renderers/html//properties/communication"
require "atome/renderers/html//properties/effect"
require "atome/renderers/html//properties/event"
require "atome/renderers/html//properties/geometry"
require "atome/renderers/html//properties/helper"
require "atome/renderers/html//properties/hierarchy"
require "atome/renderers/html//properties/identity"
require "atome/renderers/html//properties/media"
require "atome/renderers/html//properties/spatial"
require "atome/renderers/html//properties/utility"
require "atome/renderers/html//properties/visual"
require "atome/renderers/html"
# property
require "atome/properties/audio"
require "atome/properties/communication"
require "atome/properties/effect"
require "atome/properties/event"
require "atome/properties/geometry"
require "atome/properties/helper"
require "atome/properties/hierarchy"
require "atome/properties/identity"
require "atome/properties/media"
require "atome/properties/spatial"
require "atome/properties/utility"
require "atome/properties/visual"
# property processors
require "atome/processors/audio"
require "atome/processors/communication"
require "atome/processors/effect"
require "atome/processors/event"
require "atome/processors/geometry"
require "atome/processors/helper"
require "atome/processors/hierarchy"
require "atome/processors/identity"
require "atome/processors/media"
require "atome/processors/spatial"
require "atome/processors/utility"
require "atome/processors/visual"
# utilities
require "atome/helpers/internal_utilities"
# main atome builder
require "atome/builder/properties"
require "atome/builder/object"
# Atome helper (methods available at main Object level)
require "atome/helpers/atome_helpers"
# class to create a new device
require "atome/environment/device"
# elementary atomes for basic environment
require "atome/environment/initialize"
# methods to simplify object creation
require "atome/extensions/creation"